#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process

# Find the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process is running
if [[ -n "$pid" ]]; then
    # Send a SIGTERM signal to stop the process gracefully
    kill "$pid"
    echo "4-to_infinity_and_beyond process stopped."
else
    echo "4-to_infinity_and_beyond process is not running."
fi
